#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.13"
# dependencies = ["pyyaml>=6.0.2"]
# ///
r"""Convert an NVCM mock-topology blueprint into Infrahub object files.

The NVCM repository ships mock topologies under
``development/mock_topology/context/<blueprint>/`` as Nautobot-shaped YAML and
JSON (one JSON file per device, plus locations, aggregate prefixes, BGP seeds
and InfiniBand PKeys), with shared lookup tables in ``context/common/``. This
tool maps that data onto the Infrahub schema in ``schemas/`` and writes
``infrahubctl object load`` files under ``objects/<blueprint>/`` with numbered
load-order prefixes.

Nothing is invented: every attribute comes from a source field and attributes
whose source is absent are left unset. Source fields that have no home in the
schema are collected and printed at the end of a run so they can be reported.

Example:
    uv run tools/convert_mock_topology.py \
        /path/to/nv-config-manager/development/mock_topology/context/superpod

"""

from __future__ import annotations

import argparse
import hashlib
import ipaddress
import json
import logging
import re
import sys
from collections import defaultdict
from collections.abc import Iterable
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import yaml

LOGGER = logging.getLogger("convert_mock_topology")

Json = dict[str, Any]
IPNetwork = ipaddress.IPv4Network | ipaddress.IPv6Network
IPInterface = ipaddress.IPv4Interface | ipaddress.IPv6Interface

API_VERSION = "infrahub.app/v1"
IP_NAMESPACE = "default"
CUMULUS_PLATFORM = "Cumulus Linux"
DEPLOYMENT_PLACEHOLDERS = ("{{ deployment_name }}", "{{deployment_name}}")
GENERATED_HEADER = (
    "# Generated by tools/convert_mock_topology.py from blueprint {name}. Do not edit.\n"
)

DEVICE_STATUS = {
    "active": "active",
    "planned": "planned",
    "staged": "planned",
    "inventory": "planned",
    "provisioning": "provisioning",
    "provisioned": "provisioned",
    "maintenance": "maintenance",
    "decommissioned": "decommissioned",
    "decommissioning": "decommissioned",
    "disabled": "disabled",
    "offline": "disabled",
    "failed": "unknown",
}
WAN_ROLES = frozenset({"WAN", "TAN-BBR"})
COMPUTE_HINTS = ("GPU", "DGX", "COMPUTE")
MANAGEMENT_HINTS = ("UFM", "CONSOLE", "CONTROL", "JUMP", "BCM", "NMX")
SERVICE_KEYS = {
    "dns": "dns",
    "ntp": "ntp",
    "syslog": "syslog",
    "tacacs": "tacacs",
    "ztp": "ztp",
    "firmware_cache": "firmware_cache",
    "provisioning_servers": "provisioning",
}
PROFILE_KEYS = frozenset(SERVICE_KEYS) | {"dhcp", "management_prefixes"}
OPTION_SET_MATCH = {"interface_roles": "interface_role", "interface_names": "interface_name"}
HANDLED_CONTEXT_KEYS = PROFILE_KEYS | {
    "Dhcp4",
    "password_mappings",
    "site_asn",
    "intended-firmware",
    "evpn_esi_base_mac",
    "fabric-mac",
    "evpn",
    "bgp",
    "isis",
}
PHYSICAL_KIND = "InterfacePhysical"
LAG_KIND = "InterfaceLag"
VIRTUAL_KIND = "InterfaceVirtual"
INTERFACE_KIND_ORDER = (PHYSICAL_KIND, LAG_KIND, VIRTUAL_KIND)
LOCAL_PROFILE_WEIGHT = 2000


class NoAliasDumper(yaml.SafeDumper):
    """YAML dumper that never emits anchors, so repeated HFID lists stay readable."""

    def ignore_aliases(self, data: object) -> bool:  # noqa: ARG002
        """Disable anchor generation for every value."""
        return True


class Gaps:
    """Collects source values that have no home in the Infrahub schema."""

    def __init__(self) -> None:
        """Create an empty collector."""
        self._items: dict[str, set[str]] = defaultdict(set)

    def note(self, topic: str, value: object) -> None:
        """Record one unmapped value under a topic."""
        self._items[topic].add(str(value))

    def report(self) -> str:
        """Render the collected gaps as indented text."""
        lines = []
        for topic in sorted(self._items):
            values = ", ".join(sorted(self._items[topic]))
            lines.append(f"  - {topic}: {values}")
        return "\n".join(lines) if lines else "  (none)"


@dataclass
class Blueprint:
    """Everything the converter needs from one blueprint directory."""

    name: str
    deployment_name: str
    settings: Json
    devices: list[Json]
    vxlans: list[Json]
    overlay_assignments: list[tuple[str, str]]
    gaps: Gaps = field(default_factory=Gaps)

    @property
    def locations(self) -> list[Json]:
        """Location rows from locations.yaml with the deployment name rendered."""
        return [
            {**row, "name": self.render(row["name"]), "parent": self.render(row.get("parent"))}
            for row in self.settings.get("locations", [])
        ]

    @property
    def config_contexts(self) -> list[Json]:
        """Config context rows with the deployment name rendered in their scopes."""
        rendered = []
        for context in self.settings.get("config_contexts", []):
            row = dict(context)
            row["name"] = self.render(row.get("name", ""))
            for key in ("locations", "roles", "tenants", "tags"):
                row[key] = [self.render(value) for value in row.get(key, []) or []]
            rendered.append(row)
        return rendered

    @property
    def global_tenant(self) -> str | None:
        """Tenant applied to prefixes, VLANs and overlays by the design job."""
        return (self.settings.get("global_defaults") or {}).get("tenant")

    def render(self, value: str | None) -> str | None:
        """Replace the deployment-name placeholder used by the design job."""
        if value is None:
            return None
        for placeholder in DEPLOYMENT_PLACEHOLDERS:
            value = value.replace(placeholder, self.deployment_name)
        return value


@dataclass
class PrefixRecord:
    """A prefix the design job would have created, with its Nautobot decorations."""

    prefix: str
    nautobot_role: str | None
    tags: set[str]
    from_management: bool = False

    @property
    def network(self) -> IPNetwork:
        """The prefix as an ipaddress network."""
        return ipaddress.ip_network(self.prefix, strict=False)


@dataclass
class IpRecord:
    """An IP address owned by a loaded interface, or seen as a BGP peer address."""

    address: str
    device: str | None = None
    interface: str | None = None
    vrf: str | None = None
    role: str | None = None
    dhcp_reservation: bool = False
    dhcp_pool: bool = False
    description: str | None = None

    @property
    def host(self) -> str:
        """Host part of the address."""
        return str(ipaddress.ip_interface(self.address).ip)


@dataclass
class BgpSession:
    """One directed BGP session as the schema-library routing_bgp extension models it."""

    device: str
    vrf: str | None
    local_asn: int
    remote_asn: int
    remote_device: str
    remote_interface: str | None
    remote_ip: str | None
    local_ip: str | None
    peer_group: str | None

    @property
    def description(self) -> str:
        """Unique description, required by RoutingProtocol."""
        group = self.peer_group or "eBGP"
        target = ipaddress.ip_interface(self.remote_ip).ip if self.remote_ip else "unknown"
        return f"{self.device} {group} to {self.remote_device} {target}"


# --------------------------------------------------------------------------- loading


def load_yaml(path: Path) -> Json:
    """Read a YAML mapping, returning an empty mapping for missing or scalar files."""
    if not path.is_file():
        return {}
    with path.open(encoding="utf-8") as handle:
        data = yaml.safe_load(handle)
    return data if isinstance(data, dict) else {}


def load_context_yaml(directory: Path) -> Json:
    """Merge every top-level YAML mapping in a context directory."""
    merged: Json = {}
    for path in sorted(directory.glob("*.yaml")) + sorted(directory.glob("*.yml")):
        merged.update(load_yaml(path))
    return merged


def mock_serial(device_name: str) -> str:
    """Stable serial for non-Cumulus mock devices, as the design job assigns it."""
    slug = re.sub(r"[^a-z0-9]+", "", device_name.lower())
    return f"MOCK-{slug.upper()}"


def load_devices(
    devices_dir: Path, pattern: str
) -> tuple[list[Json], list[Json], list[tuple[str, str]]]:
    """Load device payloads, their VXLANs and device-scoped overlay assignments."""
    devices: list[Json] = []
    vxlans: dict[int, Json] = {}
    raw_assignments: list[tuple[str, str]] = []
    for path in sorted(devices_dir.glob(pattern)):
        payload = json.loads(path.read_text(encoding="utf-8")).get("data", {})
        device = payload.get("device")
        if not device:
            continue
        if not device.get("serial"):
            device["serial"] = mock_serial(device["name"])
        devices.append(device)
        for vxlan in payload.get("vxlans", []):
            if vxlan.get("vnid") is not None:
                vxlans.setdefault(int(vxlan["vnid"]), vxlan)
        for assignment in payload.get("overlay_assignments", []):
            object_type = assignment.get("assigned_object_type") or {}
            if (object_type.get("app_label"), object_type.get("model")) != ("dcim", "device"):
                continue
            raw_assignments.append(
                (assignment["overlay"]["name"], assignment["assigned_object_id"])
            )
    names_by_id = {device.get("id"): device["name"] for device in devices}
    assignments = sorted(
        {(overlay, names_by_id[obj]) for overlay, obj in raw_assignments if obj in names_by_id}
    )
    return devices, [vxlans[vnid] for vnid in sorted(vxlans)], assignments


def load_blueprint(
    blueprint_dir: Path, common_dir: Path, deployment: str, pattern: str
) -> Blueprint:
    """Assemble a Blueprint from the context directories."""
    settings = {**load_context_yaml(common_dir), **load_context_yaml(blueprint_dir)}
    devices, vxlans, assignments = load_devices(blueprint_dir / "devices", pattern)
    blueprint = Blueprint(
        name=blueprint_dir.name,
        deployment_name=deployment,
        settings=settings,
        devices=devices,
        vxlans=vxlans,
        overlay_assignments=assignments,
    )
    for device in devices:
        location = device.get("location") or {}
        if location.get("name"):
            location["name"] = blueprint.render(location["name"])
    return blueprint


# --------------------------------------------------------------------------- helpers


def document(kind: str, data: list[Json]) -> Json:
    """Wrap object rows in the infrahub.app/v1 Object envelope."""
    return {"apiVersion": API_VERSION, "kind": "Object", "spec": {"kind": kind, "data": data}}


def clean(mapping: Json) -> Json:
    """Drop keys whose value is unset so the attribute stays unset in Infrahub."""
    return {key: value for key, value in mapping.items() if value not in (None, [], {}, "")}


def named(value: object) -> str | None:
    """Return the ``name`` of a Nautobot reference mapping, or None."""
    if isinstance(value, dict):
        return value.get("name")
    return value if isinstance(value, str) else None


def ip_ref(address: str) -> list[str]:
    """HFID reference for an IpamIPAddress in the default namespace."""
    return [IP_NAMESPACE, address]


def as_ref(asn: int) -> list[str]:
    """HFID reference for a RoutingAutonomousSystem (GraphQL HFID components are strings)."""
    return [str(asn), as_name(asn)]


def as_name(asn: int) -> str:
    """Name given to an autonomous system object."""
    return f"AS{asn}"


def role_name(entity: Json) -> str:
    """Role name of a device or interface payload, empty when unset."""
    return named(entity.get("role")) or ""


def platform_name(device: Json) -> str | None:
    """Platform name of a device payload."""
    return named(device.get("platform"))


def is_cumulus(device: Json) -> bool:
    """Whether the device runs Cumulus Linux and is therefore NVCM managed."""
    return CUMULUS_PLATFORM in (platform_name(device) or "")


def is_management_interface(interface: Json) -> bool:
    """Apply the design job's definition of a management interface."""
    name = interface.get("name", "")
    return name == "eth0" or name.startswith("Management") or bool(interface.get("mgmt_only"))


def dhcp_flags(interface: Json, smn_device: bool) -> tuple[bool, bool]:
    """Return (pool, reservation) as the design job's ip_addresses template decides them."""
    explicit_pool = bool(interface.get("dhcp_pool"))
    reserve = bool(interface.get("dhcp_reserve")) or is_management_interface(interface)
    smn_uplink = smn_device and role_name(interface) == "Uplink"
    if explicit_pool:
        return True, False
    if reserve:
        return False, True
    return smn_uplink, False


def interface_type_label(interface: Json) -> str | None:
    """Nautobot interface type as the design template renders it, e.g. 400gbase-x-osfp."""
    itype = (interface.get("type") or "").lower()
    if not itype:
        return None
    return itype.removeprefix("a_").replace("_", "-")


def interface_kind(interface: Json) -> str:
    """Infrahub interface kind for a Nautobot interface type."""
    itype = (interface.get("type") or "").upper()
    if itype == "LAG":
        return LAG_KIND
    if itype in {"VIRTUAL", "BRIDGE"}:
        return VIRTUAL_KIND
    return PHYSICAL_KIND


def map_interface_role(interface: Json) -> str | None:
    """Return the Nautobot interface role verbatim; DcimInterface.role is free text."""
    return role_name(interface) or None


def map_device_status(status: object) -> str:
    """Map a Nautobot status name onto the adapted DcimDevice status dropdown."""
    name = (named(status) or "active").lower()
    return DEVICE_STATUS.get(name, "unknown")


def role_category(name: str) -> str:
    """Coarse NvcmDeviceRole category derived from the role name."""
    upper = name.upper()
    if name in WAN_ROLES:
        return "wan_router"
    if any(hint in upper for hint in COMPUTE_HINTS):
        return "compute"
    if any(hint in upper for hint in MANAGEMENT_HINTS):
        return "management"
    if "STORAGE" in upper and not any(part in upper for part in ("LEAF", "SPINE", "SWITCH")):
        return "storage"
    return "network"


def containing_prefix(
    network: IPNetwork, candidates: Iterable[PrefixRecord]
) -> PrefixRecord | None:
    """Smallest candidate prefix that strictly contains ``network``."""
    best: PrefixRecord | None = None
    for record in candidates:
        parent = record.network
        if network.version != parent.version or network == parent or not network.subnet_of(parent):
            continue
        if best is None or parent.prefixlen > best.network.prefixlen:
            best = record
    return best


def stable_suffix(payload: object) -> str:
    """Short deterministic hash used to name de-duplicated device-local profiles."""
    digest = hashlib.sha256(json.dumps(payload, sort_keys=True).encode()).hexdigest()
    return digest[:8]


# --------------------------------------------------------------------------- locations


class LocationIndex:
    """Resolves Nautobot locations into the Provider > Region > Site > Module hierarchy."""

    def __init__(self, blueprint: Blueprint) -> None:
        """Index the rendered location rows of a blueprint."""
        self.rows = {row["name"]: row for row in blueprint.locations}
        self.default_location = next(
            (row["name"] for row in blueprint.locations if row.get("ref") == "location"),
            next(
                (row["name"] for row in blueprint.locations if row["location_type"] == "Site"), None
            ),
        )

    def kind_of(self, name: str) -> str | None:
        """Nautobot location type of a location."""
        row = self.rows.get(name)
        return row["location_type"] if row else None

    def site_of(self, name: str | None) -> str | None:
        """Walk up to the Site that contains ``name`` (or ``name`` itself)."""
        while name and name in self.rows:
            if self.rows[name]["location_type"] == "Site":
                return name
            name = self.rows[name].get("parent")
        return None

    def region_chain(self, site: str) -> list[str]:
        """Region names from the site's parent up to the provider, innermost first."""
        chain: list[str] = []
        name = self.rows[site].get("parent")
        while name and self.kind_of(name) == "Region":
            chain.append(name)
            name = self.rows[name].get("parent")
        return chain

    def provider_of(self, site: str) -> str | None:
        """Return the provider that owns the site."""
        name = self.rows[site].get("parent")
        while name and self.kind_of(name) != "Provider":
            name = self.rows[name].get("parent")
        return name

    def sites(self) -> list[str]:
        """All site names."""
        return sorted(name for name, row in self.rows.items() if row["location_type"] == "Site")

    def modules_of(self, site: str) -> list[str]:
        """Return module names directly under a site."""
        return sorted(
            name
            for name, row in self.rows.items()
            if row["location_type"] == "Module" and row.get("parent") == site
        )

    def default_site(self) -> str | None:
        """Site hosting the default location."""
        return self.site_of(self.default_location)

    def reference(self, name: str | None) -> Json | None:
        """Inline reference for a Module or Site, as DcimDevice.location requires.

        A device without a source location lands on the blueprint's site.

        LocationHosting is a generic whose HFID is ``name`` only, while LocationModule
        keys on ``parent`` and ``name``; the server cannot resolve a module through the
        generic, so devices reference their location inline with an explicit kind.
        """
        if name is None or name not in self.rows:
            name = self.default_site()
        if name is None:
            return None
        if self.kind_of(name) == "Module":
            return {
                "kind": "LocationModule",
                "data": {"name": name, "parent": self.rows[name]["parent"]},
            }
        site = self.site_of(name)
        if site is None:
            return None
        return {
            "kind": "LocationSite",
            "data": {"name": site, "parent": self.rows[site].get("parent")},
        }


def site_asns(blueprint: Blueprint) -> dict[str, int]:
    """Site name to ASN from ``site_asn`` config contexts."""
    result: dict[str, int] = {}
    for context in blueprint.config_contexts:
        asn = (context.get("data") or {}).get("site_asn")
        if asn is None:
            continue
        for location in context.get("locations", []):
            result[location] = int(asn)
    return result


def build_locations(blueprint: Blueprint, index: LocationIndex) -> list[Json]:
    """LocationProvider tree with Regions collapsed to the site's parent region."""
    asns = site_asns(blueprint)
    providers: dict[str, dict[str, list[Json]]] = defaultdict(lambda: defaultdict(list))
    for site in index.sites():
        chain = index.region_chain(site)
        provider = index.provider_of(site)
        if not chain or provider is None:
            blueprint.gaps.note("site without Region/Provider ancestry", site)
            continue
        modules = [{"name": module} for module in index.modules_of(site)]
        site_row = clean(
            {
                "name": site,
                "status": "active",
                "site_asn": asns.get(site),
                "children": {"kind": "LocationModule", "data": modules} if modules else None,
            }
        )
        providers[provider][chain[0]].append(site_row)
    data = []
    for provider, regions in sorted(providers.items()):
        region_rows = []
        for region, sites in sorted(regions.items()):
            chain = index.region_chain(sites[0]["name"])
            description = " > ".join(reversed(chain)) if len(chain) > 1 else None
            region_rows.append(
                clean(
                    {
                        "name": region,
                        "description": description,
                        "children": {"kind": "LocationSite", "data": sites},
                    }
                )
            )
        data.append({"name": provider, "children": {"kind": "LocationRegion", "data": region_rows}})
    return [document("LocationProvider", data)]


# ------------------------------------------------------------- organisations, roles, types


def build_organizations(blueprint: Blueprint) -> list[Json]:
    """Manufacturers and tenants from common data plus anything a device references."""
    manufacturers = set(blueprint.settings.get("manufacturers") or [])
    manufacturers |= set((blueprint.settings.get("device_types") or {}).keys())
    tenants = {row["name"] for row in blueprint.settings.get("tenants") or []}
    if blueprint.global_tenant:
        tenants.add(blueprint.global_tenant)
    for device in blueprint.devices:
        manufacturers.add(device["device_type"]["manufacturer"]["name"])
        if named(device.get("tenant")):
            tenants.add(named(device["tenant"]))
    return [
        document("OrganizationManufacturer", [{"name": name} for name in sorted(manufacturers)]),
        document("OrganizationTenant", [{"name": name} for name in sorted(tenants)]),
    ]


def build_roles(blueprint: Blueprint) -> list[Json]:
    """NvcmDeviceRole objects for every device role seen or scoped by a config context."""
    managed: dict[str, bool] = {}
    for device in blueprint.devices:
        role = role_name(device)
        if role:
            managed[role] = managed.get(role, False) or is_cumulus(device)
    for context in blueprint.config_contexts:
        for role in context.get("roles", []):
            managed.setdefault(role, False)
    for row in blueprint.settings.get("common_roles") or blueprint.settings.get("roles") or []:
        if named(row):
            managed.setdefault(named(row), False)
    data = [
        {"name": role, "category": role_category(role), "managed_by_nvcm": managed[role]}
        for role in sorted(managed)
    ]
    return [document("NvcmDeviceRole", data)]


def build_tags(blueprint: Blueprint) -> list[Json]:
    """BuiltinTag objects for every tag attached to a device or an interface."""
    tags: set[str] = set()
    for device in blueprint.devices:
        tags |= {named(tag) for tag in device.get("tags", []) if named(tag)}
        for interface in device.get("interfaces", []):
            tags |= {named(tag) for tag in interface.get("tags") or [] if named(tag)}
    return [document("BuiltinTag", [{"name": name} for name in sorted(tags)])] if tags else []


def build_platforms_and_types(blueprint: Blueprint) -> list[Json]:
    """DcimPlatform and DcimDeviceType from common tables plus the devices themselves."""
    platforms: dict[str, str | None] = {}
    for row in blueprint.settings.get("platforms") or []:
        platforms[row["name"]] = row.get("manufacturer")
    for device in blueprint.devices:
        if platform_name(device):
            platforms.setdefault(platform_name(device), None)
    types: dict[str, Json] = {}
    for manufacturer, models in (blueprint.settings.get("device_types") or {}).items():
        for model in models:
            types[model["model"]] = clean(
                {
                    "name": model["model"],
                    "manufacturer": manufacturer,
                    "part_number": model.get("part_number"),
                    "height": model.get("u_height"),
                    "full_depth": model.get("is_full_depth"),
                }
            )
    for device in blueprint.devices:
        device_type = device["device_type"]
        types.setdefault(
            device_type["model"],
            {"name": device_type["model"], "manufacturer": device_type["manufacturer"]["name"]},
        )
    platform_rows = [
        clean({"name": name, "manufacturer": maker}) for name, maker in sorted(platforms.items())
    ]
    return [
        document("DcimPlatform", platform_rows),
        document("DcimDeviceType", [types[name] for name in sorted(types)]),
    ]


# --------------------------------------------------------------------------- VRFs and VLANs


def collect_vrfs(blueprint: Blueprint) -> dict[str, str | None]:
    """VRF name to route distinguisher across devices, interfaces and VXLANs."""
    vrfs: dict[str, str | None] = {}

    def merge(vrf: object) -> None:
        if isinstance(vrf, dict) and vrf.get("name"):
            vrfs[vrf["name"]] = vrf.get("rd") or vrfs.get(vrf["name"])

    for device in blueprint.devices:
        for vrf in device.get("vrfs", []):
            merge(vrf)
        for interface in device.get("interfaces", []):
            merge(interface.get("vrf"))
    for vxlan in blueprint.vxlans:
        merge(vxlan.get("vrf"))
    return vrfs


def device_vrfs(device: Json) -> list[str]:
    """VRF names a device participates in, as vrf_device_assignments derives them."""
    names = {
        vrf["name"] for vrf in device.get("vrfs", []) if isinstance(vrf, dict) and vrf.get("name")
    }
    for interface in device.get("interfaces", []):
        if named(interface.get("vrf")):
            names.add(named(interface["vrf"]))
    return sorted(names)


def build_vrfs(blueprint: Blueprint) -> list[Json]:
    """IpamVRF objects named in the source data."""
    vrfs = collect_vrfs(blueprint)
    data = [clean({"name": name, "vrf_rd": rd}) for name, rd in sorted(vrfs.items())]
    return [document("IpamVRF", data)]


def vlan_label(vlan: Json) -> str:
    """VLAN name as the design job derives it."""
    return vlan.get("name") or f"Vlan{vlan['vid']}"


def collect_vlans(blueprint: Blueprint) -> dict[int, str]:
    """VLAN id to name from interfaces and L2 VXLANs."""
    vlans: dict[int, str] = {}
    for device in blueprint.devices:
        for interface in device.get("interfaces", []):
            candidates = [interface.get("untagged_vlan"), *(interface.get("tagged_vlans") or [])]
            for vlan in candidates:
                if isinstance(vlan, dict) and vlan.get("vid"):
                    vlans[int(vlan["vid"])] = vlan_label(vlan)
    for vxlan in blueprint.vxlans:
        vlan = vxlan.get("vlan")
        if isinstance(vlan, dict) and vlan.get("vid"):
            vlans[int(vlan["vid"])] = vlan_label(vlan)
    return vlans


def vlan_group_name(site: str) -> str:
    """Name of the per-site VLAN group."""
    return f"{site} VLANs"


def build_vlan_groups(blueprint: Blueprint, index: LocationIndex) -> list[Json]:
    """One IpamVLANGroup per site holding every VLAN as an inline IpamVLAN child."""
    vlans = collect_vlans(blueprint)
    site = index.default_site()
    if not vlans or site is None:
        return []
    rows = [
        {"name": name, "vlan_id": vid, "status": "active"} for vid, name in sorted(vlans.items())
    ]
    group = {
        "name": vlan_group_name(site),
        "scope": index.reference(site),
        "vlans": {"kind": "IpamVLAN", "data": rows},
    }
    blueprint.gaps.note(
        "VLAN helper addresses (vlan_to_helper_address)", "no source in mock topology"
    )
    return [document("IpamVLANGroup", [group])]


# --------------------------------------------------------------------------- prefixes and addresses


def collect_prefixes(blueprint: Blueprint) -> list[PrefixRecord]:
    """Prefixes the design job creates: aggregates, /31 links and DHCP subnets."""
    records: dict[str, PrefixRecord] = {}
    for aggregate in blueprint.settings.get("aggregate_prefixes") or []:
        records[aggregate["prefix"]] = PrefixRecord(
            aggregate["prefix"], aggregate.get("role"), set(aggregate.get("tags") or [])
        )
    aggregates = list(records.values())
    dhcp_subnets: dict[str, bool] = {}
    for device in blueprint.devices:
        smn = role_name(device).startswith("SMN")
        for interface in device.get("interfaces", []):
            pool, reservation = dhcp_flags(interface, smn)
            for address in interface.get("ip_addresses", []):
                if not address.get("address"):
                    continue
                network = ipaddress.ip_network(address["address"], strict=False)
                if pool or reservation:
                    from_mgmt = is_management_interface(interface) and not pool
                    dhcp_subnets[str(network)] = dhcp_subnets.get(str(network), False) or from_mgmt
                if network.prefixlen in (31, 127) and str(network) not in records:
                    parent = containing_prefix(network, aggregates)
                    records[str(network)] = PrefixRecord(
                        str(network), parent.nautobot_role if parent else None, set()
                    )
    for prefix, from_mgmt in dhcp_subnets.items():
        if prefix not in records:
            parent = containing_prefix(ipaddress.ip_network(prefix), aggregates)
            records[prefix] = PrefixRecord(prefix, parent.nautobot_role if parent else None, set())
        records[prefix].tags.add("dhcp-subnet")
        records[prefix].from_management = from_mgmt
    return sorted(records.values(), key=lambda record: (record.network.prefixlen, record.network))


def prefix_flags(record: PrefixRecord, gaps: Gaps) -> Json:
    """Booleans replacing the role-aggregate and uc-jumphost tags; other tags are gaps."""
    for tag in record.tags - {"role-aggregate", "uc-jumphost", "dhcp-subnet"}:
        gaps.note("prefix tag without home", tag)
    return {
        "site_aggregate": True if "role-aggregate" in record.tags else None,
        "uc_jumphost": True if "uc-jumphost" in record.tags else None,
    }


def build_prefixes(
    blueprint: Blueprint, index: LocationIndex, records: list[PrefixRecord]
) -> list[Json]:
    """IpamPrefix objects scoped to the site, Nautobot role name kept verbatim."""
    site = index.default_site()
    scope = index.reference(site) if site else None
    data = []
    for record in records:
        has_children = any(
            other.network != record.network and other.network.subnet_of(record.network)
            for other in records
            if other.network.version == record.network.version
        )
        data.append(
            clean(
                {
                    "prefix": record.prefix,
                    "ip_namespace": IP_NAMESPACE,
                    "status": "active",
                    "role": record.nautobot_role,
                    **prefix_flags(record, blueprint.gaps),
                    "member_type": "prefix" if has_children else "address",
                    "tenant": blueprint.global_tenant,
                    "scope": scope,
                }
            )
        )
    return [document("IpamPrefix", data)]


def collect_ip_records(blueprint: Blueprint) -> dict[str, IpRecord]:
    """Interface addresses keyed by address, first owner wins on duplicates."""
    records: dict[str, IpRecord] = {}
    for device in blueprint.devices:
        smn = role_name(device).startswith("SMN")
        for interface in device.get("interfaces", []):
            pool, reservation = dhcp_flags(interface, smn)
            management = is_management_interface(interface)
            for address in interface.get("ip_addresses", []):
                value = address.get("address")
                if not value:
                    continue
                if value in records:
                    blueprint.gaps.note("duplicate address across interfaces", value)
                    continue
                records[value] = IpRecord(
                    address=value,
                    device=device["name"],
                    interface=interface["name"],
                    vrf=named(interface.get("vrf")),
                    role="management" if management else None,
                    dhcp_reservation=reservation,
                    dhcp_pool=pool,
                )
    return records


def build_ip_addresses(records: dict[str, IpRecord]) -> list[Json]:
    """IpamIPAddress objects; the interface link is set from the interface side."""
    data = []
    for address in sorted(records, key=lambda value: ipaddress.ip_interface(value)):
        record = records[address]
        data.append(
            clean(
                {
                    "address": record.address,
                    "ip_namespace": IP_NAMESPACE,
                    "status": "active",
                    "role": record.role,
                    "description": record.description,
                    "vrf": record.vrf,
                    "dhcp_reservation": True if record.dhcp_reservation else None,
                }
            )
        )
    return [document("IpamIPAddress", data)]


# --------------------------------------------------------------------------- devices and interfaces


def isis_metrics(config_context: Json) -> dict[str, int]:
    """Interface name to IS-IS metric from the ``isis.interfaces`` config context key."""
    interfaces = (config_context.get("isis") or {}).get("interfaces") or {}
    metrics: dict[str, int] = {}
    if isinstance(interfaces, dict):
        for name, value in interfaces.items():
            metric = value.get("metric") if isinstance(value, dict) else value
            if metric is not None:
                metrics[name] = int(metric)
    elif isinstance(interfaces, list):
        for entry in interfaces:
            if isinstance(entry, dict) and entry.get("name") and entry.get("metric") is not None:
                metrics[entry["name"]] = int(entry["metric"])
    return metrics


def bundle_number(name: str) -> int | None:
    """LAG bundle number parsed from names such as ``bond2``."""
    match = re.search(r"(\d+)$", name)
    return int(match.group(1)) if match else None


def interface_object(
    device: Json, interface: Json, kind: str, kinds: dict[str, str], gaps: Gaps
) -> Json | None:
    """Infrahub data for one interface, or None when a mandatory field is missing."""
    name = interface["name"]
    data: Json = {
        "name": name,
        "description": interface.get("description"),
        "status": "active" if interface.get("enabled", True) else "disabled",
        "role": map_interface_role(interface),
        "interface_type": interface_type_label(interface),
        "mtu": interface.get("mtu"),
        "mac_address": interface.get("mac_address"),
        "ib_guid": (interface.get("custom_fields") or {}).get("ib_guid"),
        "isis_metric": isis_metrics(device.get("config_context") or {}).get(name),
        "vrf": named(interface.get("vrf")),
        "tags": [named(tag) for tag in interface.get("tags") or [] if named(tag)],
        "untagged_vlan": vlan_label(interface["untagged_vlan"])
        if interface.get("untagged_vlan")
        else None,
        "tagged_vlan": [vlan_label(vlan) for vlan in interface.get("tagged_vlans") or []],
        "ip_addresses": [
            ip_ref(ip["address"]) for ip in interface.get("ip_addresses", []) if ip.get("address")
        ],
    }
    if kind == LAG_KIND:
        data["bundle_number"] = bundle_number(name)
        if data["bundle_number"] is None:
            gaps.note("LAG without a parseable bundle number", f"{device['name']} {name}")
            return None
        data["bundle_members"] = [
            [device["name"], named(member)] for member in interface.get("member_interfaces") or []
        ]
    parent = named(interface.get("parent_interface"))
    if kind == VIRTUAL_KIND and parent and kinds.get(parent) in (PHYSICAL_KIND, LAG_KIND):
        data["parent_interface"] = [device["name"], parent]
    return clean(data)


def interface_objects(device: Json, gaps: Gaps) -> list[Json]:
    """Inline interface children ordered so members and parents load first."""
    kinds = {
        interface["name"]: interface_kind(interface) for interface in device.get("interfaces", [])
    }
    rows: list[Json] = []
    for wanted in INTERFACE_KIND_ORDER:
        for interface in device.get("interfaces", []):
            if kinds[interface["name"]] != wanted:
                continue
            data = interface_object(device, interface, wanted, kinds, gaps)
            if data is not None:
                rows.append({"kind": wanted, "data": data})
    return rows


def router_id_interface(device: Json) -> str | None:
    """Name of the router-id interface on the device's first BGP routing instance."""
    for instance in device.get("bgp_routing_instances") or []:
        interfaces = (instance.get("router_id") or {}).get("interfaces") or []
        if interfaces and named(interfaces[0]):
            return named(interfaces[0])
    return None


def primary_address(device: Json) -> str | None:
    """First IPv4 address on the declared primary interface."""
    wanted = device.get("primary_ip4_interface")
    for interface in device.get("interfaces", []):
        if interface["name"] != wanted:
            continue
        for address in interface.get("ip_addresses", []):
            if address.get("ip_version") == 4 and address.get("address"):
                return address["address"]
    return None


def note_unhandled_context(config_context: Json, gaps: Gaps) -> None:
    """Record config-context keys the converter does not map anywhere."""
    for key in config_context:
        if key not in HANDLED_CONTEXT_KEYS:
            gaps.note("config_context key without home", key)


def device_object(device: Json, blueprint: Blueprint, index: LocationIndex) -> Json | None:
    """DcimDevice row with inline interfaces."""
    if not role_name(device):
        blueprint.gaps.note("device without role (device_role is mandatory)", device["name"])
        return None
    context = device.get("config_context") or {}
    note_unhandled_context(context, blueprint.gaps)
    bgp = context.get("bgp") or {}
    custom = device.get("custom_fields") or {}
    tags = [named(tag) for tag in device.get("tags", []) if named(tag)]
    primary = primary_address(device)
    return clean(
        {
            "name": device["name"],
            "status": map_device_status(device.get("status")),
            "serial_number": device.get("serial"),
            "device_type": device["device_type"]["model"],
            "platform": platform_name(device),
            "device_role": role_name(device),
            "location": index.reference((device.get("location") or {}).get("name")),
            "tenant": named(device.get("tenant")),
            "tags": tags,
            "primary_address": ip_ref(primary) if primary else None,
            "route_server": True if "route-server" in tags else None,
            "intended_firmware_version": (context.get("intended-firmware") or {}).get("version"),
            "bgp_default_asn": int(bgp["asn"]) if bgp.get("asn") is not None else None,
            "bgp_local_asn": int(bgp["local-asn"]) if bgp.get("local-asn") is not None else None,
            "evpn_esi_base_mac": context.get("evpn_esi_base_mac"),
            "evpn_fabric_mac": context.get("fabric-mac"),
            "evpn_df_preference": (context.get("evpn") or {}).get("df-preference"),
            "bgp_router_id_interface": router_id_interface(device),
            "alias": custom.get("alias"),
            "external_id": custom.get("nico_machine_id"),
            "vrfs": device_vrfs(device),
            "interfaces": interface_objects(device, blueprint.gaps),
        }
    )


def build_devices(blueprint: Blueprint, index: LocationIndex) -> list[Json]:
    """DcimDevice objects for every device in the blueprint."""
    rows = [device_object(device, blueprint, index) for device in blueprint.devices]
    return [document("DcimDevice", [row for row in rows if row])]


# --------------------------------------------------------------------------- cables


def build_cables(blueprint: Blueprint) -> list[Json]:
    """One DcimCable per physical link whose both ends are loaded devices."""
    kinds = {
        device["name"]: {
            intf["name"]: interface_kind(intf) for intf in device.get("interfaces", [])
        }
        for device in blueprint.devices
    }
    seen: set[tuple[tuple[str, str], tuple[str, str]]] = set()
    for device in blueprint.devices:
        for interface in device.get("interfaces", []):
            remote = interface.get("connected_interface") or {}
            remote_device, remote_name = named(remote.get("device")), remote.get("name")
            if not remote_device or not remote_name or remote_device not in kinds:
                continue
            if remote_name not in kinds[remote_device]:
                blueprint.gaps.note(
                    "cable to an interface missing on the remote device",
                    f"{remote_device} {remote_name}",
                )
                continue
            local = (device["name"], interface["name"])
            far = (remote_device, remote_name)
            if kinds[local[0]][local[1]] != PHYSICAL_KIND or kinds[far[0]][far[1]] != PHYSICAL_KIND:
                blueprint.gaps.note("cable on a non-physical interface", f"{local} -> {far}")
                continue
            seen.add(tuple(sorted((local, far))))  # type: ignore[arg-type]
    data = []
    for end_a, end_b in sorted(seen):
        data.append(
            {
                "label": f"{end_a[0]}:{end_a[1]}--{end_b[0]}:{end_b[1]}",
                "status": "connected",
                "connected_endpoints": [
                    {"kind": PHYSICAL_KIND, "data": {"device": end_a[0], "name": end_a[1]}},
                    {"kind": PHYSICAL_KIND, "data": {"device": end_b[0], "name": end_b[1]}},
                ],
            }
        )
    return [document("DcimCable", data)]


# --------------------------------------------------------------------------- BGP


def device_asns(blueprint: Blueprint) -> dict[str, int]:
    """Device name to ASN from the YAML seed and the JSON routing instances."""
    asns: dict[str, int] = {}
    for row in blueprint.settings.get("bgp_routing_instances") or []:
        if row.get("device") and row.get("asn") is not None:
            asns[row["device"]] = int(row["asn"])
    for device in blueprint.devices:
        for instance in device.get("bgp_routing_instances") or []:
            asn = (instance.get("autonomous_system") or {}).get("asn")
            if asn is not None:
                asns[device["name"]] = int(asn)
    return asns


def interface_ipv4(device: Json, name: str | None) -> str | None:
    """First IPv4 address on a named interface of a device payload."""
    for interface in device.get("interfaces", []):
        if interface["name"] == name:
            for address in interface.get("ip_addresses", []):
                if address.get("ip_version") == 4 and address.get("address"):
                    return address["address"]
    return None


def local_address_for(
    device: Json, remote: str | None, router_id_interface: str | None
) -> str | None:
    """Local session address: the on-link address for a p2p peer, else the router-id."""
    if remote is None:
        return None
    remote_interface = ipaddress.ip_interface(remote)
    if remote_interface.network.prefixlen < remote_interface.max_prefixlen:
        for interface in device.get("interfaces", []):
            for address in interface.get("ip_addresses", []):
                if not address.get("address"):
                    continue
                local = ipaddress.ip_interface(address["address"])
                if local.network == remote_interface.network and local.ip != remote_interface.ip:
                    return address["address"]
    return interface_ipv4(device, router_id_interface)


def sessions_from_instances(device: Json) -> list[BgpSession]:
    """Sessions from the ``bgp_routing_instances[].endpoints`` block of a device payload."""
    sessions: list[BgpSession] = []
    router_id = router_id_interface(device)
    for instance in device.get("bgp_routing_instances") or []:
        local_asn = int(instance["autonomous_system"]["asn"])
        for endpoint in instance.get("endpoints") or []:
            peer = endpoint.get("peer") or {}
            peer_instance = peer.get("routing_instance") or {}
            remote_device = named(peer_instance.get("device"))
            remote_asn = (peer_instance.get("autonomous_system") or {}).get("asn")
            if not remote_device or remote_asn is None:
                continue
            source = peer.get("source_interface") or {}
            remote_ip = next(
                (
                    ip["address"]
                    for ip in source.get("ip_addresses", [])
                    if ip.get("ip_version") == 4
                ),
                peer.get("source_ip"),
            )
            sessions.append(
                BgpSession(
                    device=device["name"],
                    vrf=named((endpoint.get("source_interface") or {}).get("vrf")),
                    local_asn=local_asn,
                    remote_asn=int(remote_asn),
                    remote_device=remote_device,
                    remote_interface=source.get("name"),
                    remote_ip=remote_ip,
                    local_ip=local_address_for(device, remote_ip, router_id),
                    peer_group=named(endpoint.get("peer_group")),
                )
            )
    return sessions


def sessions_from_seed(blueprint: Blueprint, asns: dict[str, int]) -> list[BgpSession]:
    """Both directions of each ``bgp_peerings`` seed row whose devices are loaded."""
    devices = {device["name"]: device for device in blueprint.devices}
    sessions: list[BgpSession] = []
    for row in blueprint.settings.get("bgp_peerings") or []:
        ends = (
            (row.get("device"), row.get("source_interface")),
            (row.get("peer_device"), row.get("peer_source_interface")),
        )
        for (local, local_intf), (remote, remote_intf) in (ends, ends[::-1]):
            if (
                local not in devices
                or remote not in devices
                or local not in asns
                or remote not in asns
            ):
                blueprint.gaps.note(
                    "bgp_peerings row with unknown device or ASN", f"{local} <-> {remote}"
                )
                continue
            local_vrf = next(
                (
                    named(i.get("vrf"))
                    for i in devices[local]["interfaces"]
                    if i["name"] == local_intf
                ),
                None,
            )
            sessions.append(
                BgpSession(
                    device=local,
                    vrf=local_vrf,
                    local_asn=asns[local],
                    remote_asn=asns[remote],
                    remote_device=remote,
                    remote_interface=remote_intf,
                    remote_ip=interface_ipv4(devices[remote], remote_intf),
                    local_ip=interface_ipv4(devices[local], local_intf),
                    peer_group=None,
                )
            )
    return sessions


def collect_sessions(blueprint: Blueprint, asns: dict[str, int]) -> list[BgpSession]:
    """All sessions, de-duplicated on (device, remote address, peer group)."""
    unique: dict[tuple[str, str | None, str | None], BgpSession] = {}
    for device in blueprint.devices:
        for session in sessions_from_instances(device):
            unique.setdefault((session.device, session.remote_ip, session.peer_group), session)
    for session in sessions_from_seed(blueprint, asns):
        unique.setdefault((session.device, session.remote_ip, session.peer_group), session)
    return sorted(unique.values(), key=lambda session: (session.device, session.description))


def peer_group_description(device: str, name: str) -> str:
    """Return the unique description of a per-device RoutingBGPPeerGroup."""
    return f"{name} peer group on {device}"


def session_object(session: BgpSession) -> Json:
    """RoutingBGPSession row."""
    return clean(
        {
            "description": session.description,
            "status": "active",
            "session_type": "external" if session.local_asn != session.remote_asn else "internal",
            "device": session.device,
            "vrf": session.vrf,
            "local_as": as_ref(session.local_asn),
            "remote_as": as_ref(session.remote_asn),
            "local_ip": ip_ref(session.local_ip) if session.local_ip else None,
            "remote_ip": ip_ref(session.remote_ip) if session.remote_ip else None,
            "peer_group": [session.device, session.peer_group] if session.peer_group else None,
        }
    )


def build_bgp(blueprint: Blueprint, ip_records: dict[str, IpRecord]) -> list[Json]:
    """Autonomous systems, per-device peer groups and one session per directed peering."""
    asns = device_asns(blueprint)
    sessions = collect_sessions(blueprint, asns)
    tenants = {device["name"]: named(device.get("tenant")) for device in blueprint.devices}
    organisations: dict[int, str | None] = {}
    members: dict[int, set[str]] = defaultdict(set)
    for device_name, asn in asns.items():
        if device_name in tenants:
            members[asn].add(device_name)
            organisations.setdefault(asn, tenants[device_name])
        organisations.setdefault(asn, None)
    for session in sessions:
        organisations.setdefault(session.remote_asn, None)
        if session.remote_ip and session.remote_ip not in ip_records:
            owner = f"{session.remote_device} {session.remote_interface or ''}".strip()
            ip_records[session.remote_ip] = IpRecord(
                address=session.remote_ip, description=f"BGP peer address of {owner}"
            )
    as_rows = [
        clean(
            {
                "name": as_name(asn),
                "asn": asn,
                "organization": organisations[asn],
                "devices": sorted(members[asn]),
            }
        )
        for asn in sorted(organisations)
    ]
    groups = sorted({(s.device, s.peer_group) for s in sessions if s.peer_group})
    group_rows = [
        {
            "name": group,
            "description": peer_group_description(device, group),
            "status": "active",
            "device": device,
        }
        for device, group in groups
    ]
    return [
        document("RoutingAutonomousSystem", as_rows),
        document("RoutingBGPPeerGroup", group_rows),
        document("RoutingBGPSession", [session_object(session) for session in sessions]),
    ]


def build_device_status(blueprint: Blueprint) -> list[Json]:
    """NvcmDeviceStatus for every Cumulus Linux device, all flags enabled."""
    data = [
        {
            "device": device["name"],
            "render_enabled": True,
            "ztp_enabled": True,
            "deploy_enabled": True,
            "backup_enabled": True,
        }
        for device in blueprint.devices
        if is_cumulus(device)
    ]
    return [document("NvcmDeviceStatus", data)]


def endpoint_sets(data: Json) -> list[Json]:
    """NvcmServiceEndpointSet rows for the service keys present in a context."""
    rows = []
    for key, service in SERVICE_KEYS.items():
        block = data.get(key)
        if isinstance(block, dict) and (block.get("ipv4") or block.get("ipv6")):
            rows.append(
                clean({"service": service, "ipv4": block.get("ipv4"), "ipv6": block.get("ipv6")})
            )
    return rows


def dhcp_server_sets(data: Json) -> list[Json]:
    """NvcmDhcpServerSet rows for every provider block under ``dhcp`` except ``options``."""
    rows = []
    for name, block in (data.get("dhcp") or {}).items():
        if name == "options" or not isinstance(block, dict):
            continue
        rows.append(clean({"name": name, "ipv4": block.get("ipv4"), "ipv6": block.get("ipv6")}))
    return rows


def dhcp_option_sets(data: Json, gaps: Gaps) -> list[Json]:
    """NvcmDhcpOptionSet rows from ``dhcp.options.interface_roles`` and ``interface_names``."""
    rows = []
    options = (data.get("dhcp") or {}).get("options") or {}
    for source_key, match_kind in OPTION_SET_MATCH.items():
        for match_value, block in (options.get(source_key) or {}).items():
            rows.append(
                clean(
                    {
                        "name": f"{match_kind}:{match_value}",
                        "match_kind": match_kind,
                        "match_value": match_value,
                        "subnet_options": block.get("subnet_options"),
                        "reservation_options": block.get("reservation_options"),
                        "subnet_config": block.get("subnet_config"),
                        "client_id_template": block.get("client_id_template"),
                    }
                )
            )
    for key in set(options) - set(OPTION_SET_MATCH):
        gaps.note("dhcp.options key without home", key)
    return rows


def profile_object(name: str, data: Json, scope: Json, gaps: Gaps) -> Json | None:
    """NvcmServiceProfile row, or None when the context carries no service data."""
    endpoints = endpoint_sets(data)
    servers = dhcp_server_sets(data)
    option_rows = dhcp_option_sets(data, gaps)
    prefixes = data.get("management_prefixes") or {}
    if not (endpoints or servers or option_rows or prefixes):
        return None
    return clean(
        {
            "name": name,
            "description": scope.get("description"),
            "weight": scope.get("weight"),
            "is_active": scope.get("is_active"),
            "management_prefixes_ipv4": prefixes.get("ipv4"),
            "management_prefixes_ipv6": prefixes.get("ipv6"),
            "locations": scope.get("locations"),
            "device_roles": scope.get("roles"),
            "platforms": scope.get("platforms"),
            "devices": scope.get("devices"),
            "endpoint_sets": {"kind": "NvcmServiceEndpointSet", "data": endpoints}
            if endpoints
            else None,
            "dhcp_servers": {"kind": "NvcmDhcpServerSet", "data": servers} if servers else None,
            "dhcp_option_sets": {"kind": "NvcmDhcpOptionSet", "data": option_rows}
            if option_rows
            else None,
        }
    )


def local_context_groups(blueprint: Blueprint) -> dict[str, tuple[Json, list[str]]]:
    """Device-local service payloads grouped by content, name to (payload, devices)."""
    groups: dict[str, tuple[Json, list[str]]] = {}
    for device in blueprint.devices:
        context = device.get("config_context") or {}
        payload = {key: context[key] for key in sorted(context) if key in PROFILE_KEYS}
        if not payload:
            continue
        name = f"device-local-services-{stable_suffix(payload)}"
        groups.setdefault(name, (payload, []))[1].append(device["name"])
    return groups


def build_service_profiles(blueprint: Blueprint) -> list[Json]:
    """Profiles from location/role config contexts plus de-duplicated device-local ones."""
    rows = []
    for context in blueprint.config_contexts:
        data = context.get("data") or {}
        note_unhandled_context(data, blueprint.gaps)
        for key in ("tenants", "tags"):
            if context.get(key):
                blueprint.gaps.note(f"config context scope '{key}' without home", context["name"])
        profile = profile_object(context["name"], data, context, blueprint.gaps)
        if profile:
            rows.append(profile)
    for name, (payload, devices) in sorted(local_context_groups(blueprint).items()):
        scope = {
            "description": "Device local config context, merged by content",
            "weight": LOCAL_PROFILE_WEIGHT,
            "devices": sorted(devices),
        }
        profile = profile_object(name, payload, scope, blueprint.gaps)
        if profile:
            rows.append(profile)
    return [document("NvcmServiceProfile", rows)]


def build_credentials(blueprint: Blueprint) -> list[Json]:
    """NvcmCredentialMapping from ``password_mappings`` in device and location contexts."""
    mappings: dict[str, Json] = {}

    def add(scope_key: str, scope_value: str, username: str, entry: Json) -> None:
        slug = re.sub(r"[^a-z0-9]+", "-", scope_value.lower()).strip("-")
        name = f"{slug}-{username}"
        row = mappings.setdefault(
            name,
            {
                "name": name,
                "username": username,
                "secret_name": entry.get("password"),
                "rotation": entry.get("rotation"),
                "role": entry.get("role"),
            },
        )
        scoped = row.setdefault(scope_key, [])
        if scope_value not in scoped:
            scoped.append(scope_value)

    for device in blueprint.devices:
        platform = platform_name(device)
        for username, entry in (
            (device.get("config_context") or {}).get("password_mappings") or {}
        ).items():
            if platform:
                add("platforms", platform, username, entry)
            else:
                add("devices", device["name"], username, entry)
    for context in blueprint.config_contexts:
        for username, entry in ((context.get("data") or {}).get("password_mappings") or {}).items():
            for location in context.get("locations", []):
                add("locations", location, username, entry)
    return [document("NvcmCredentialMapping", [clean(mappings[name]) for name in sorted(mappings)])]


# --------------------------------------------------------------------------- DHCP and firmware


def option_definitions(blueprint: Blueprint) -> list[Json]:
    """NvcmDhcpOptionDefinition rows from every ``Dhcp4.option-def`` block."""
    definitions: dict[tuple[str, str], Json] = {}
    sources = [
        (context.get("data") or {}, context.get("locations", []))
        for context in blueprint.config_contexts
    ]
    sources += [(device.get("config_context") or {}, []) for device in blueprint.devices]
    for data, locations in sources:
        for entry in (data.get("Dhcp4") or {}).get("option-def") or []:
            key = (entry.get("space") or "dhcp4", entry["name"])
            row = definitions.setdefault(
                key,
                {
                    "name": entry["name"],
                    "code": entry["code"],
                    "space": key[0],
                    "option_type": entry.get("type"),
                    "array": entry.get("array"),
                    "record_types": entry.get("record-types"),
                    "encapsulate": entry.get("encapsulate"),
                    "locations": [],
                },
            )
            row["locations"] = sorted(set(row["locations"]) | set(locations))
    return [clean(row) for _, row in sorted(definitions.items())]


def pool_ranges(hosts: Iterable[str]) -> list[tuple[str, str]]:
    """Merge hosts into contiguous (start, end) ranges."""
    ordered = sorted({ipaddress.ip_address(host) for host in hosts})
    ranges: list[tuple[str, str]] = []
    start = previous = None
    for host in ordered:
        if previous is not None and int(host) == int(previous) + 1:
            previous = host
            continue
        if start is not None and previous is not None:
            ranges.append((str(start), str(previous)))
        start = previous = host
    if start is not None and previous is not None:
        ranges.append((str(start), str(previous)))
    return ranges


def pool_gateways(blueprint: Blueprint, ip_records: dict[str, IpRecord]) -> dict[str, str]:
    """Prefix to gateway address as ``_load_prefix_gateway_relationships`` derives it."""
    gateways: dict[str, str] = {}
    by_host = {record.host: record.address for record in ip_records.values()}
    for device in blueprint.devices:
        for interface in device.get("interfaces", []):
            if not interface.get("dhcp_pool"):
                continue
            for address in interface.get("ip_addresses", []):
                if not address.get("address"):
                    continue
                local = ipaddress.ip_interface(address["address"])
                if local.network.prefixlen not in (31, 127):
                    continue
                gateway = next(str(host) for host in local.network if host != local.ip)
                if gateway in by_host:
                    gateways.setdefault(str(local.network), by_host[gateway])
                else:
                    blueprint.gaps.note("DHCP gateway address not loaded", gateway)
    return gateways


def build_dhcp(
    blueprint: Blueprint, records: list[PrefixRecord], ip_records: dict[str, IpRecord]
) -> list[Json]:
    """Option definitions plus one NvcmDhcpScope per prefix the design tagged dhcp-subnet."""
    dhcp_records = [record for record in records if "dhcp-subnet" in record.tags]
    pools_by_prefix: dict[str, list[str]] = defaultdict(list)
    for record in ip_records.values():
        if not record.dhcp_pool:
            continue
        owner = containing_prefix(ipaddress.ip_network(record.address, strict=False), dhcp_records)
        exact = next(
            (
                r
                for r in dhcp_records
                if r.network == ipaddress.ip_network(record.address, strict=False)
            ),
            None,
        )
        target = exact or owner
        if target:
            pools_by_prefix[target.prefix].append(record.host)
    gateways = pool_gateways(blueprint, ip_records)
    scopes = []
    for record in dhcp_records:
        pools = [
            {"name": f"{record.prefix} {start}-{end}", "start": start, "end": end}
            for start, end in pool_ranges(pools_by_prefix.get(record.prefix, []))
        ]
        scopes.append(
            clean(
                {
                    "name": record.prefix,
                    "prefix": [IP_NAMESPACE, record.prefix],
                    "enabled": True,
                    "gateway": ip_ref(gateways[record.prefix])
                    if record.prefix in gateways
                    else None,
                    "pools": {"kind": "NvcmDhcpPool", "data": pools} if pools else None,
                }
            )
        )
    return [
        document("NvcmDhcpOptionDefinition", option_definitions(blueprint)),
        document("NvcmDhcpScope", scopes),
    ]


def build_firmware_targets(
    blueprint: Blueprint, roles: set[str], platforms: set[str]
) -> list[Json]:
    """NvcmFirmwareTarget rows from location-firmware-targets shaped config contexts."""
    by_upper = {role.upper(): role for role in roles}
    rows = []
    for context in blueprint.config_contexts:
        data = context.get("data") or {}
        for key, block in data.items():
            if key in HANDLED_CONTEXT_KEYS or not isinstance(block, dict):
                continue
            role = by_upper.get(key.upper().replace("_", "-"))
            targets = {p: v for p, v in block.items() if p in platforms and isinstance(v, str)}
            if role is None or not targets:
                continue
            for location in context.get("locations", []):
                for platform, version in targets.items():
                    rows.append(
                        {
                            "location": location,
                            "device_role": role,
                            "platform": platform,
                            "desired_version": version,
                        }
                    )
    return [document("NvcmFirmwareTarget", rows)] if rows else []


# --------------------------------------------------------------------------- overlays


def vxlan_row(vxlan: Json) -> Json:
    """NvcmVxlan component row."""
    return clean(
        {
            "vni": int(vxlan["vnid"]),
            "vni_type": vxlan.get("vni_type"),
            "l3_vlan_id": vxlan.get("l3_vlan_id"),
            "vlan": vlan_label(vxlan["vlan"]) if vxlan.get("vlan") else None,
            "vrf": named(vxlan.get("vrf")),
        }
    )


def build_overlays(blueprint: Blueprint, index: LocationIndex) -> list[Json]:
    """VXLAN EVPN overlays from device payloads and IB PKey overlays from ib_pkeys.yaml."""
    location = index.reference(index.default_location)
    by_overlay: dict[str, list[Json]] = defaultdict(list)
    for vxlan in blueprint.vxlans:
        by_overlay[named(vxlan.get("overlay")) or vxlan["name"]].append(vxlan_row(vxlan))
    assignments: dict[str, list[str]] = defaultdict(list)
    for overlay, device in blueprint.overlay_assignments:
        assignments[overlay].append(device)
    rows = []
    for name in sorted(set(by_overlay) | set(assignments)):
        assigned = [{"name": device, "device": device} for device in sorted(set(assignments[name]))]
        rows.append(
            clean(
                {
                    "name": name,
                    "isolation_type": "vxlan_evpn",
                    "status": "active",
                    "location": location,
                    "tenant": blueprint.global_tenant,
                    "vxlans": {"kind": "NvcmVxlan", "data": by_overlay[name]}
                    if by_overlay[name]
                    else None,
                    "assignments": {"kind": "NvcmOverlayAssignment", "data": assigned}
                    if assigned
                    else None,
                }
            )
        )
    for overlay in blueprint.settings.get("ib_pkey_overlays") or []:
        pkeys = [
            clean(
                {
                    "pkey": pkey["pkey"],
                    "partition_name": pkey.get("name"),
                    "default_membership": pkey.get("membership_type"),
                }
            )
            for pkey in overlay.get("pkeys") or []
        ]
        rows.append(
            clean(
                {
                    "name": overlay["name"],
                    "description": overlay.get("description"),
                    "isolation_type": "ib_pkey",
                    "status": "active",
                    "location": location,
                    "tenant": blueprint.global_tenant,
                    "pkeys": {"kind": "NvcmInfinibandPkey", "data": pkeys} if pkeys else None,
                }
            )
        )
    return [document("NvcmOverlay", rows)]


# --------------------------------------------------------------------------- output


def write_documents(path: Path, documents: list[Json], blueprint_name: str) -> int:
    """Write non-empty documents to one file; return the number of top-level objects."""
    populated = [doc for doc in documents if doc["spec"]["data"]]
    if not populated:
        LOGGER.info("skipping %s, nothing to write", path.name)
        return 0
    chunks = [GENERATED_HEADER.format(name=blueprint_name)]
    for doc in populated:
        chunks.append(
            "---\n"
            + yaml.dump(doc, Dumper=NoAliasDumper, sort_keys=False, width=1000, allow_unicode=True)
        )
    path.write_text("".join(chunks), encoding="utf-8")
    count = sum(len(doc["spec"]["data"]) for doc in populated)
    LOGGER.info("wrote %s (%d objects)", path.name, count)
    return count


def convert(blueprint: Blueprint, output_dir: Path) -> dict[str, int]:
    """Run every builder in load order and write the object files."""
    index = LocationIndex(blueprint)
    prefix_records = collect_prefixes(blueprint)
    ip_records = collect_ip_records(blueprint)
    bgp_documents = build_bgp(blueprint, ip_records)  # adds BGP peer addresses to ip_records
    roles = {row["name"] for row in build_roles(blueprint)[0]["spec"]["data"]}
    platforms = {row["name"] for row in build_platforms_and_types(blueprint)[0]["spec"]["data"]}
    files: list[tuple[str, list[Json]]] = [
        ("00-organizations.yml", build_organizations(blueprint)),
        ("10-locations.yml", build_locations(blueprint, index)),
        ("20-roles.yml", build_roles(blueprint) + build_tags(blueprint)),
        ("30-platforms-device-types.yml", build_platforms_and_types(blueprint)),
        (
            "40-namespaces-vrfs-vlans.yml",
            build_vrfs(blueprint) + build_vlan_groups(blueprint, index),
        ),
        ("50-prefixes.yml", build_prefixes(blueprint, index, prefix_records)),
        ("55-ip-addresses.yml", build_ip_addresses(ip_records)),
        ("60-devices.yml", build_devices(blueprint, index)),
        ("80-cables.yml", build_cables(blueprint)),
        ("85-bgp.yml", bgp_documents),
        ("90-nvcm-state.yml", build_device_status(blueprint)),
        ("91-service-profiles.yml", build_service_profiles(blueprint)),
        ("92-dhcp.yml", build_dhcp(blueprint, prefix_records, ip_records)),
        ("93-firmware.yml", build_firmware_targets(blueprint, roles, platforms)),
        ("94-credentials.yml", build_credentials(blueprint)),
        ("95-overlays.yml", build_overlays(blueprint, index)),
    ]
    output_dir.mkdir(parents=True, exist_ok=True)
    for stale in output_dir.glob("*.yml"):
        stale.unlink()
    return {
        name: write_documents(output_dir / name, documents, blueprint.name)
        for name, documents in files
    }


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    """Command line arguments."""
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument(
        "blueprint_dir", type=Path, help="mock_topology/context/<blueprint> directory"
    )
    parser.add_argument(
        "--common-dir", type=Path, help="context/common directory (default: sibling of blueprint)"
    )
    parser.add_argument(
        "--output-dir", type=Path, help="destination (default: objects/<blueprint> in the repo)"
    )
    parser.add_argument(
        "--deployment-name", default="test", help="value for {{ deployment_name }} (default: test)"
    )
    parser.add_argument(
        "--device-glob", default="*.json", help="glob for devices/*.json (default: *.json)"
    )
    parser.add_argument("-v", "--verbose", action="store_true", help="debug logging")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    """Entry point."""
    args = parse_args(argv)
    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO, format="%(levelname)s %(message)s"
    )
    blueprint_dir = args.blueprint_dir.resolve()
    common_dir = (args.common_dir or blueprint_dir.parent / "common").resolve()
    output_dir = (
        args.output_dir or Path(__file__).resolve().parent.parent / "objects" / blueprint_dir.name
    )
    blueprint = load_blueprint(blueprint_dir, common_dir, args.deployment_name, args.device_glob)
    LOGGER.info("loaded %d devices from %s", len(blueprint.devices), blueprint_dir)
    counts = convert(blueprint, output_dir)
    print(f"\nWrote {sum(counts.values())} top-level objects to {output_dir}")
    print("Source data without a home in the schema:")
    print(blueprint.gaps.report())
    return 0


if __name__ == "__main__":
    sys.exit(main())
